logo: adr's note. # add logo name
title: adr's note
description: > # this means to ignore newlines until "baseurl:"
  Welcome to adr's blog!
  Sheng-Hao Ma (aaaddress1, adr) is a core member of CHROOT Security Group and TDOHacker security community in Taiwan. 
  He has over 10-year experience in reverse engineering, machine language, and Intel 8086. 
  He experts in Windows vulnerability, Exploit, and Reverse Engineering. 
  
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://30cm.tw" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: mountains.mp4 # add banner video. Add your video file to the folder video
banner-title: adr's note # add banner title
banner-desc: It seems like aaaddress1 leaves some notes here ┐(´∀｀)┌ # add banner description

# Author settings
author-pic: face.jpg # your photo
author-name: Sheng-Hao Ma # your name
about-author: > # about author
  Sheng-Hao Ma (aaaddress1, adr) is a core member of CHROOT Security Group and TDOHacker security community in Taiwan. 
  He has over 10-year experience in reverse engineering, machine language, and Intel 8086. 
  He experts in Windows vulnerability, and Reverse Engineering. 
  
  Moreover, Sheng-Hao Ma was also a speaker at Black Hat, DEFCON USA, VXCON, HITCON (Hackers In Taiwan Conference), 
  SITCON (Students In Taiwan Conference) and iThome#Chatbot.
 
email: aaaddress1@chroot.org # your email
phone: (496)-169-6557 # your pnone number
website: https://30cm.tw # you website

# Social link
google_url:    # add url link
twitter_url: https://twitter.com/aaaddress1  # add url link
instagram_url: # add url link
pinterest_url: # add url link
dribbble_url:  # add url link
facebook_url: https://www.facebook.com/aaaddress1 # add url link

# Disqus
discus_identifier: adrs-note # add your discus identifier
layout: default
comments:
  provider : disqus
  disqus :
    short_name : adrs-note    # 將內容替換成剛剛在disqus上申請的site name


# Newsletter
mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics:

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
